### ISSUE TITLE
同学方便交流以下这个么？

### ISSUE THREAD

**Issue by CaiQiuYu** [opconty/keras_zsd#1]
我用比赛的词向量和原作者提供的glove词表训练出来的模型测试的时候输出的分数都是0，不知道你有没有碰到过这个问题

**Comment by opconty** [comment]
我没做这个比赛

**Comment by CaiQiuYu** [comment]
> 我没做这个比赛

你有在自己的数据上跑过么，就很奇怪预测的分数都是0，感觉是词向量的问题，不知道你是怎么处理的

**Comment by opconty** [comment]
这个项目跑的结果很不错,没有出现你说的全为0的情况,,具体看代码吧, 目前比较忙,谢谢支持

**Comment by CaiQiuYu** [comment]
> 这个项目跑的结果很不错,没有出现你说的全为0的情况,,具体看代码吧, 目前比较忙,谢谢支持

感谢！

**Comment by CaiQiuYu** [comment]
> 这个项目跑的结果很不错,没有出现你说的全为0的情况,,具体看代码吧, 目前比较忙,谢谢支持

最后问一下，方便说下你的词向量是怎么获取的吗？
